version: '3.8'
services:
  customer-management:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
