

CREATE TABLE public.CUSTOMERS
(
    ID           BIGINT       NOT NULL,
    FIRST_NAME   VARCHAR(40) NOT NULL,
    MIDDLE_NAME  VARCHAR(40),
    FIRST_SURNAME    VARCHAR(40) NOT NULL,
    SECOND_SURNAME VARCHAR(40),
    EMAIL        VARCHAR(40) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    ADDRESS      VARCHAR(200) NOT NULL,
    COUNTRY VARCHAR(4) NOT NULL,
    DEMONYM      VARCHAR(40) NOT NULL
);

ALTER TABLE CUSTOMERS
    ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID);

CREATE SEQUENCE CUSTOMERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE CUSTOMERS
    ALTER COLUMN ID SET DEFAULT NEXTVAL('CUSTOMERS_SEQ');
