CREATE TABLE CUSTOMERS
(
    ID           BIGINT       NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    DEMONYM      VARCHAR(255) NOT NULL,
)

ALTER TABLE CUSTOMERS
    ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID);

ALTER TABLE CUSTOMERS
    ADD CONSTRAINT CUSTOMERS_UK UNIQUE (EMAIL);
