

CREATE TABLE public.CUSTOMERS
(
    ID           BIGINT       NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(255) NOT NULL,
    DEMONYM      VARCHAR(255) NOT NULL
);

ALTER TABLE CUSTOMERS
    ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID);

CREATE SEQUENCE CUSTOMERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE CUSTOMERS
    ALTER COLUMN ID SET DEFAULT NEXTVAL('CUSTOMERS_SEQ');
